name: GitHub Actions Generate PDF
run-name: ${{ github.actor }} is generating PDF
on:
  workflow_run:
    workflows: ["GitHub Actions Deploy"]
    types:
      - completed
permissions:
  contents: write
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set NODE_ENV to development
        run: echo "NODE_ENV=development" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          mkdir build/output
          node ./scripts/pdf.js ${{ secrets.CV_URL_OUTPUT_JSON }}

      - name: Install Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript

      - name: Compress PDF with Ghostscript
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=build/output/cv_nicolastorre_fr.pdf build/output/cv_fr.pdf |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=build/output/cv_nicolastorre_en.pdf build/output/cv_en.pdf

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
